/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationIndexRouteImport } from './routes/organization/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as PatientsIndexRouteImport } from './routes/patients/index'
import { Route as PatientsManageRouteImport } from './routes/patients/manage'
import { Route as ProvidersManageRouteImport } from './routes/providers/manage'
import { Route as SpinnerIndexRouteImport } from './routes/spinner/index'
import { Route as UserManagementIndexRouteImport } from './routes/user-management/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIndexRoute = OrganizationIndexRouteImport.update({
  id: '/organization/',
  path: '/organization/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsManageRoute = PatientsManageRouteImport.update({
  id: '/patients/manage',
  path: '/patients/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersManageRoute = ProvidersManageRouteImport.update({
  id: '/providers/manage',
  path: '/providers/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const SpinnerIndexRoute = SpinnerIndexRouteImport.update({
  id: '/spinner/',
  path: '/spinner/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementIndexRoute = UserManagementIndexRouteImport.update({
  id: '/user-management/',
  path: '/user-management/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patients/manage': typeof PatientsManageRoute
  '/providers/manage': typeof ProvidersManageRoute
  '/organization/': typeof OrganizationIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/spinner/': typeof SpinnerIndexRoute
  '/user-management/': typeof UserManagementIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patients/manage': typeof PatientsManageRoute
  '/providers/manage': typeof ProvidersManageRoute
  '/organization': typeof OrganizationIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/patients': typeof PatientsIndexRoute
  '/spinner': typeof SpinnerIndexRoute
  '/user-management': typeof UserManagementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patients/manage': typeof PatientsManageRoute
  '/providers/manage': typeof ProvidersManageRoute
  '/organization/': typeof OrganizationIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/spinner/': typeof SpinnerIndexRoute
  '/user-management/': typeof UserManagementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/patients/manage'
    | '/providers/manage'
    | '/organization/'
    | '/organizations/'
    | '/patients/'
    | '/spinner/'
    | '/user-management/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/patients/manage'
    | '/providers/manage'
    | '/organization'
    | '/organizations'
    | '/patients'
    | '/spinner'
    | '/user-management'
  id:
    | '__root__'
    | '/'
    | '/patients/manage'
    | '/providers/manage'
    | '/organization/'
    | '/organizations/'
    | '/patients/'
    | '/spinner/'
    | '/user-management/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatientsManageRoute: typeof PatientsManageRoute
  ProvidersManageRoute: typeof ProvidersManageRoute
  OrganizationIndexRoute: typeof OrganizationIndexRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
  SpinnerIndexRoute: typeof SpinnerIndexRoute
  UserManagementIndexRoute: typeof UserManagementIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/': {
      id: '/organization/'
      path: '/organization'
      fullPath: '/organization/'
      preLoaderRoute: typeof OrganizationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/manage': {
      id: '/patients/manage'
      path: '/patients/manage'
      fullPath: '/patients/manage'
      preLoaderRoute: typeof PatientsManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/manage': {
      id: '/providers/manage'
      path: '/providers/manage'
      fullPath: '/providers/manage'
      preLoaderRoute: typeof ProvidersManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spinner/': {
      id: '/spinner/'
      path: '/spinner'
      fullPath: '/spinner/'
      preLoaderRoute: typeof SpinnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management/': {
      id: '/user-management/'
      path: '/user-management'
      fullPath: '/user-management/'
      preLoaderRoute: typeof UserManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatientsManageRoute: PatientsManageRoute,
  ProvidersManageRoute: ProvidersManageRoute,
  OrganizationIndexRoute: OrganizationIndexRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  PatientsIndexRoute: PatientsIndexRoute,
  SpinnerIndexRoute: SpinnerIndexRoute,
  UserManagementIndexRoute: UserManagementIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
