// PreToolUse Edit|Write|MultiEdit — AGENTS.md §0.7: generated / load-bearing files
// are never edited without explicit instruction.
import { readFileSync } from "node:fs";
import path from "node:path";
import { readInput, deny, rel, ROOT } from "./lib.mjs";

const input = readInput();
const file = rel(input.tool_input?.file_path);
if (!file) process.exit(0);

const PROTECTED = [
  [/^\.npmrc$/, ".npmrc (node-linker=hoisted — Expo breaks without it)"],
  [/(^|\/)routeTree\.gen\.ts$/, "routeTree.gen.ts (generated by the TanStack Router Vite plugin — run pnpm dev:admin or pnpm build to regenerate)"],
  [/(^|\/)expo-env\.d\.ts$/, "expo-env.d.ts (generated, committed on purpose)"],
];
for (const [re, why] of PROTECTED) {
  if (re.test(file)) deny(`AGENTS.md §0.7: do not edit ${why}. Ask the user for explicit instruction if this is really the task.`);
}

// pnpm-workspace.yaml may change, but the lightningcss override must survive.
if (file === "pnpm-workspace.yaml") {
  const ti = input.tool_input || {};
  let next;
  if (typeof ti.content === "string") {
    next = ti.content;
  } else {
    let cur = "";
    try { cur = readFileSync(path.join(ROOT, file), "utf8"); } catch { cur = ""; }
    const edits = Array.isArray(ti.edits) ? ti.edits : [{ old_string: ti.old_string, new_string: ti.new_string, replace_all: ti.replace_all }];
    next = cur;
    for (const e of edits) {
      if (typeof e.old_string !== "string") continue;
      next = e.replace_all ? next.split(e.old_string).join(e.new_string ?? "") : next.replace(e.old_string, e.new_string ?? "");
    }
  }
  if (!/^\s*lightningcss:\s*1\.30\.1\s*$/m.test(next)) {
    deny("AGENTS.md §0.7: the `lightningcss: 1.30.1` override in pnpm-workspace.yaml is a NativeWind v5 requirement and must not be removed or changed.");
  }
}
